import 'package:json_annotation/json_annotation.dart';

part 'examdetails.g.dart';  // This will be generated by the json_serializable package

@JsonSerializable()
class ExamResponse {
  final int? exam_id;
  final String? exam_name;
  final String? exam_date;
  final String? exam_location;
  final int? exam_duration;
  final int? question_count;
  final int? candidate_count;
  final int? serial_number;
  final String? candidate_name;
  final String? candidate_school;
  final String? candidate_class_level;
  final String? candidate_picture;
  final int? scholar_id;
  final int? question_number;
  final int? correct_answer;
  final int? correct_answers;
  final int? incorrect_answers;
  final String? grade;

  ExamResponse({
    this.exam_id,
    this.exam_name,
    this.exam_date,
    this.exam_location,
    this.exam_duration,
    this.question_count,
    this.candidate_count,
    this.serial_number,
    this.candidate_name,
    this.candidate_school,
    this.candidate_class_level,
    this.candidate_picture,
    this.scholar_id,
    this.question_number,
    this.correct_answer,
    this.correct_answers,
    this.incorrect_answers,
    this.grade,
  });

  // From JSON method (converts JSON to ExamResponse object)
  factory ExamResponse.fromJson(Map<String, dynamic> json) => _$ExamResponseFromJson(json);

  // To JSON method (converts ExamResponse object to JSON)
  Map<String, dynamic> toJson() => _$ExamResponseToJson(this);
}
